{% set cctools_version = '927.0.2' %}
{% set ld64_version = '450.3' %}
{% set native_compiler_subdir = 'linux-64' %}  # [linux]
{% set libcxx_min = "4" %}

package:
  name: cctools-and-ld64
  version: {{ ld64_version }}

source:
  # latest commit from branch {{ cctools_version }}-ld64-{{ ld64_version }}
  - url: https://github.com/tpoechtrager/cctools-port/archive/ae83e7fcdeb2b8bd838b6008f1972bd853fa0e76.tar.gz
    sha256: 3149168c513166515406280506c04837f47f6a40723d6ab06b1b7c131a3938b0
    patches:
      - dont_link_with_libcxxabi.patch
      - 530-ld64-add-conda-specific-env-vars-to-modify-lib-search-paths.patch
      - fix_spart_pc.patch

build:
  number: 0
  skip: True  # [win]
  ignore_run_exports:
    - zlib

requirements:
  build:
    - clangxx  # [linux]
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    #- xar
    # We only use the static library from this and only get away with that as it depends on nothing.
    - zlib
    - llvmdev
    - libuuid   # [linux]
    - tapi

outputs:
  - name: cctools
    version: {{ cctools_version }}
    script: install-cctools.sh
    build:
      activate_in_script: True
      ignore_run_exports:
        - zlib
    requirements:
      build:
        - {{ compiler('cxx') }}
        - autoconf
        - automake
        - make
      host:
        - zlib
        - llvmdev
        # - llvm
        - tapi
        - libcxx >={{libcxx_min}}  # [osx]
        - {{ pin_subpackage("ld64", max_pin="x.x") }}
      run:
        - libcxx >={{libcxx_min}}  # [osx]
        - {{ pin_subpackage("ld64", max_pin="x.x") }}
    test:
      commands:
        - test -f $PREFIX/libexec/as/x86_64/as
        - test -f $PREFIX/bin/{{ macos_machine }}-as
        - test -f $PREFIX/bin/{{ macos_machine }}-ranlib
        - test -f $PREFIX/bin/{{ macos_machine }}-ar
        - test -f $PREFIX/bin/{{ macos_machine }}-otool
        # Check that otool is functioning
        - $PREFIX/bin/{{ macos_machine }}-otool -l $PREFIX/bin/{{ macos_machine }}-otool
        - test -f $PREFIX/bin/{{ macos_machine }}-install_name_tool
        - test -f $PREFIX/bin/{{ macos_machine }}-strip
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/APPLE_LICENSE
      summary: Assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files

  - name: ld64
    version: {{ ld64_version }}
    script: install-ld64.sh
    build:
      activate_in_script: True
      missing_dso_whitelist:
        - /usr/lib/libxar.1.dylib  # [osx]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - autoconf
        - automake
        - make
      host:
        - llvmdev
        - clangdev
        - tapi
        - libcxx >={{libcxx_min}}  # [osx]
        - libuuid  # [linux]
      run:
        - {{ pin_compatible("tapi") }}
        - libcxx >={{libcxx_min}}  # [osx]
      run_constrained:
        - {{ pin_compatible("clang") }}
    test:
      commands:
        - test -f $PREFIX/bin/{{ macos_machine }}-ld
      downstreams:
        - gfortran_osx-64  # [osx]
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/ld64/APPLE_LICENSE
      summary: Darwin Mach-O linker

about:
  home: https://github.com/tpoechtrager/cctools-port
  license: APSL-2.0
  license_family: Other
  license_file: cctools/APPLE_LICENSE
  summary: Assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files. Darwin Mach-O linker.

extra:
  recipe-maintainers:
    - isuruf
    - mingwandroid
    - davidbrochart
